// Lieux, quartiers et plans d'eau affichés sur la carte.
export const KCOL = { hotel: '#b07a3a', savoir: '#e07b39', monument: '#d6452f', marche: '#f2b705', eau: '#2f8fb0', transport: '#5b6bd6', culte: '#8a5cc2', plage: '#e2a35a', institution: '#3d9a6a', quartier: '#c96f3b' };
export const PLACES = [
  { id: 'etoile', name: "Place de l'Étoile Rouge", kind: 'Monument', k: 'monument', lat: 6.37149, lon: 2.40979, h: 52, view: [270, 1.08, 0.7],
    text: "Le grand carrefour où se rejoignent cinq voies. Sur l'île centrale, deux étoiles rouges posées à plat, une flèche blanche et, au sommet, la statue de bronze d'un homme portant une houe et une gerbe. Le monument date du milieu des années 1970, sous Mathieu Kérékou." },
  { id: 'dantokpa', name: 'Marché Dantokpa', kind: 'Marché', k: 'marche', lat: 6.3727, lon: 2.4352, h: 16, view: [400, 1.05, 2.3],
    text: "« Tokpa » pour tout le monde : l'un des plus grands marchés à ciel ouvert d'Afrique de l'Ouest, sur la rive ouest de la lagune. Des parasols à perte de vue, des sacs d'oignons et de riz, des étals sous la tôle et le grand bâtiment à l'enseigne du marché." },
  { id: 'amazone', name: "Place de l'Amazone", kind: 'Monument', k: 'monument', lat: 6.34895, lon: 2.40755, h: 36, view: [170, 1.2, 0.15],
    text: "Statue de bronze de 30 mètres inaugurée en 2022, en hommage aux Agoodjié, les guerrières du royaume du Dahomey : fusil dressé, sabre à la main, sur un socle de pierre noire. L'esplanade dallée s'étend face à l'océan." },
  { id: 'marina', name: 'Palais de la Marina', kind: 'Présidence', k: 'institution', lat: 6.35163, lon: 2.40908, h: 20, view: [300, 1.05, 2.9],
    text: "Siège de la présidence de la République, le long du boulevard de la Marina : un long bâtiment beige sur piliers, ses bandeaux vitrés bleutés, ses drapeaux et ses palmiers royaux." },
  { id: 'congres', name: 'Palais des Congrès', kind: 'Institution', k: 'institution', lat: 6.34775, lon: 2.40501, h: 26, view: [340, 1.02, 3.0],
    text: "Inauguré en 2003 et inspiré des tata somba du nord du Bénin : des tambours blancs ceints d'une frise de triangles sombres, percés chacun d'un oculus doré, reliés par une aile basse à claustras." },
  { id: 'cathedrale', name: 'Cathédrale Notre-Dame', kind: 'Lieu de culte', k: 'culte', lat: 6.35637, lon: 2.43917, h: 44, view: [150, 1.15, -1.25],
    text: "La cathédrale Notre-Dame de Miséricorde, à Ganhi, rayée de rouge et de blanc de la base au pignon, avec son clocher carré planté à côté de la nef, à deux pas de l'ancien pont." },
  { id: 'port', name: 'Port autonome', kind: 'Port', k: 'transport', lat: 6.3465, lon: 2.4235, h: 30, view: [1100, 0.98, 0.5],
    text: "Le principal port du Bénin et la porte d'entrée maritime de pays sans accès à la mer comme le Niger et le Burkina Faso. Portiques à conteneurs le long du môle, grues mobiles, navires à quai et grandes pirogues peintes au port de pêche." },
  { id: 'corniche', name: 'Corniche Est', kind: 'Promenade', k: 'plage', lat: 6.3555, lon: 2.4508, h: 10, view: [230, 1.15, 0.6],
    text: "La Corniche Est d'Akpakpa : un trottoir pavé, une piste de jogging couleur brique, des lampadaires à double crosse, de jeunes cocotiers et des épis de roches noires qui s'avancent dans l'Atlantique." },
  { id: 'aeroport', name: 'Aéroport Cardinal Bernardin Gantin', kind: 'Aéroport', k: 'transport', lat: 6.35421, lon: 2.38586, h: 18, view: [520, 1.02, 0.35],
    text: "L'aéroport international, en pleine ville à Cadjèhoun : l'aérogare et sa grande enseigne jaune, les tentes blanches de l'entrée, les avions au stationnement et la piste 06/24 qui longe la côte." },
  { id: 'stade', name: "Stade de l'Amitié", kind: 'Stade', k: 'institution', lat: 6.38614, lon: 2.3794, h: 30, view: [380, 0.95, 0.5],
    text: "Le stade Général Mathieu Kérékou, à Kouhounou, terrain de l'équipe nationale, les Guépards : piste rouge, tribunes jaunes, vertes et rouges, tribune couverte et pylônes d'éclairage en treillis." },
  { id: 'chenal', name: 'Chenal de Cotonou', kind: 'Lagune', k: 'eau', lat: 6.3665, lon: 2.4405, h: 8, view: [1300, 1.0, 0.9],
    text: "Le bras de lagune qui coupe la ville en deux et relie le lac Nokoué à l'océan. Trois ponts le franchissent pour rejoindre Akpakpa ; les pirogues longent la rive de Dantokpa." },
  { id: 'fidjrosse', name: 'Plage de Fidjrossè', kind: 'Plage', k: 'plage', lat: 6.3485, lon: 2.3665, h: 8, view: [300, 1.12, 0.15],
    text: "La plage de l'ouest, le long de la route des Pêches : cocotiers, paillotes, buvettes et pirogues tirées sur le sable. La barre y est forte : la baignade est dangereuse." },
  { id: 'haievive', name: 'Haie Vive', kind: 'Quartier', k: 'quartier', lat: 6.3552, lon: 2.3976, h: 10, view: [380, 1.0, 0.4],
    text: "Le quartier des restaurants, des bars et des maquis, tout près de l'aéroport. Rues arborées et terrasses sous les parasols : c'est là que Cotonou sort le soir." },
  { id: 'nokoue', name: 'Lac Nokoué', kind: 'Lagune', k: 'eau', lat: 6.432, lon: 2.425, h: 6, view: [3600, 1.08, 0.3],
    text: "La grande lagune au nord de la ville. Les pêcheurs y plantent des acadjas, des enclos de branchages où le poisson vient se réfugier ; on les voit en lignes brunes à la surface de l'eau." },
  { id: 'bioguera', name: 'Carrefour Bio Guéra', kind: 'Monument', k: 'monument', lat: 6.35015, lon: 2.38752, h: 16, view: [210, 1.05, 0.9],
    text: "Au carrefour d'Erevan, l'un des plus fréquentés de Cotonou, la statue équestre de Bio Guéra, figure de la résistance à la colonisation française dans le nord du pays. Juste à côté, le grand magasin Erevan." },
  { id: 'bceao', name: 'Tour BCEAO', kind: 'Architecture', k: 'institution', lat: 6.35333, lon: 2.42639, h: 70, view: [330, 1.05, 0.5],
    text: "Le siège béninois de la Banque centrale des États de l'Afrique de l'Ouest : 64 mètres et 16 étages, le plus haut immeuble du Bénin, inauguré en 1994. Sur chaque façade, quatre colonnes de treize cauris dorés — l'ancienne monnaie — et cinq de plus au sommet ; devant, une fontaine entourée de sept bassins." },
  { id: 'zongo', name: 'Mosquée de Zongo', kind: 'Lieu de culte', k: 'culte', lat: 6.35680, lon: 2.42637, h: 40, view: [240, 1.08, 0.7],
    text: "La grande mosquée du quartier Zongo, au centre-ville, et ses minarets blancs qui dominent les toits." },
  { id: 'uac', name: "Université d'Abomey-Calavi", kind: 'Campus', k: 'savoir', lat: 6.4148, lon: 2.3428, h: 16, view: [380, 1.02, 0.6],
    text: "La plus grande université publique du Bénin, née en 1970 sous le nom d'Université du Dahomey : l'entrée principale aux piliers orangés, les amphis, la bibliothèque centrale et l'École polytechnique." },
  { id: 'seme', name: 'Sèmè One', kind: 'Innovation', k: 'savoir', lat: 6.35277, lon: 2.39503, h: 18, view: [190, 1.12, 0.3],
    text: "Le premier campus de Sèmè City, la cité internationale de l'innovation et du savoir, ouvert en 2020 aux Cocotiers : façade ocre rythmée de lames colorées. Le grand campus est en construction à Ouidah." },
  { id: 'calavi', name: 'Abomey-Calavi', kind: 'Ville', k: 'quartier', lat: 6.4476, lon: 2.3600, h: 12, view: [900, 1.0, 0.9],
    text: "La grande ville voisine, au bord du lac Nokoué : le carrefour Kpota, le marché de Calavi-Tokpa et l'embarcadère d'où partent les pirogues pour Ganvié." },
  { id: 'ganvie', name: 'Ganvié', kind: 'Cité lacustre', k: 'eau', lat: 6.4681, lon: 2.39, h: 12, view: [240, 1.12, 0.6],
    text: "Le village sur pilotis du lac Nokoué, la « Venise de l'Afrique ». Plus de cinq mille maisons de planches sous la tôle ou la paille, des pirogues partout, des jacinthes d'eau et un marché flottant. On s'y rend en pirogue depuis Abomey-Calavi." },
  { id: 'jardin', name: "Jardin de l'Amazone", kind: 'Jardin public', k: 'quartier', lat: 6.35075, lon: 2.40710, h: 22, view: [260, 1.0, 2.6],
    text: "En face de la statue de l'Amazone, de l'autre côté du boulevard de la Marina : des pelouses en forme de feuilles, des allées sinueuses et une rangée de seize grands pylônes effilés le long de la route. Une longue promenade monte jusqu'à l'avenue Jean-Paul II." },
  { id: 'cite', name: 'Cité ministérielle', kind: 'Administration', k: 'institution', lat: 6.35114, lon: 2.40458, h: 26, view: [420, 1.0, 2.7],
    text: "Mise en service en octobre 2025 sur l'ancien site de l'hôtel Croix du Sud : dix bâtiments de six niveaux en travertin clair et fenêtres en bandeau vert-bleu, autour de cours plantées et d'un bassin. Seize ministères y travaillent ; un bâtiment-parking abrite un restaurant de mille places." },
  { id: 'usa', name: 'Ambassade des États-Unis', kind: 'Ambassade', k: 'institution', lat: 6.35083, lon: 2.40302, h: 18, view: [260, 1.0, 2.6],
    text: "Le complexe de l'ambassade américaine, sur le boulevard de la Marina, juste à côté de la Cité ministérielle : bâtiments en L derrière un haut mur de blocs gris, panneaux solaires sur les parkings." },
  { id: 'golden', name: 'Golden Tulip Le Diplomate', kind: 'Hôtel', k: 'hotel', lat: 6.34902, lon: 2.40329, h: 22, view: [230, 1.05, 2.9],
    text: "Hôtel de cinq niveaux face à l'ambassade des États-Unis : façade blanche aux petites fenêtres profondes, grand mur rouge sang-de-bœuf, bloc gris et enseigne bleu marine à la tulipe dorée." },
  { id: 'novotel', name: 'Novotel Orisha et Ibis', kind: 'Hôtels', k: 'hotel', lat: 6.34880, lon: 2.40120, h: 16, view: [320, 1.0, 2.8],
    text: "Deux hôtels dans le même jardin de sept hectares : le Novotel Orisha en V, toits gris et liseré bleu, et l'Ibis, longue barre de trois niveaux au toit débordant rouge. Un étang et un petit pavillon bordent l'allée." },
  { id: 'mtn', name: 'Siège de MTN Bénin', kind: 'Entreprise', k: 'institution', lat: 6.34943, lon: 2.39872, h: 34, view: [230, 1.05, 2.5],
    text: "Le siège de l'opérateur MTN, boulevard de la Marina : un immeuble de verre vert réfléchissant, un grand pan jaune MTN sur la façade ouest et un pylône rouge et blanc sur le toit. En face, de l'autre côté du boulevard, Nigeria House, l'ambassade du Nigeria." },
  { id: 'dome', name: 'Le Dôme et le Pavillon', kind: 'Sofitel Marina', k: 'hotel', lat: 6.35000, lon: 2.39630, h: 26, view: [280, 1.0, 2.8],
    text: "L'ancien Centre international de conférences de 1995, rénové par le Sofitel : un grand cône à facettes couleur bronze, illuminé le soir. À côté, le Pavillon, aux ailettes dorées et à la verrière bleue, abrite deux salles de cinéma, un casino et un club. Une allée de nuages blancs les relie à l'hôtel." },
  { id: 'superu', name: 'Erevan · Super U', kind: 'Centre commercial', k: 'marche', lat: 6.34895, lon: 2.38694, h: 12, view: [220, 1.05, 3.0],
    text: "Le centre commercial Erevan, au carrefour Bio Guéra : une grande boîte orange brûlé, « SUPER » en lettres bleues et le logo U, un grand parking devant et le totem « EREVAN » au bord de la route." },
  { id: 'murport', name: 'Mur des fresques du port', kind: 'Art urbain', k: 'monument', lat: 6.35010, lon: 2.41600, h: 8, view: [140, 1.2, 2.9],
    text: "Le long du port, côté boulevard de la Marina : un kilomètre et demi de fresques. À l'ouest, « The New Bénin » du festival Effet Graff (2022) ; sur l'ancien Hôtel du Port, « Coexistence » du Brésilien Eduardo Kobra (2023) ; puis la Marina Boulev'art Gallery, où 27 artistes de 13 pays ont peint depuis 2024." },
  { id: 'agl', name: 'Siège d’AGL', kind: 'Logistique', k: 'transport', lat: 6.35085, lon: 2.41977, h: 32, view: [200, 1.05, 2.8],
    text: "Le siège d'Africa Global Logistics (ex-Bolloré), inauguré en 2017 face au port : deux blocs de verre bleu cadrés de blanc, six étages, un auvent en vague devant l'entrée." },
  { id: 'porte', name: 'Porte du Non-Retour', kind: 'Mémorial · Ouidah', k: 'monument', lat: 6.32414, lon: 2.08918, h: 16, view: [120, 1.12, 2.75],
    text: "Le mémorial érigé en 1995 sur la plage de Ouidah, au bout de la Route des Esclaves, à près de 4 km de la place Chacha. Sa grande arche regarde l'océan d'où partaient les navires négriers ; ses frises de bronze montrent les captifs enchaînés qui marchent vers la mer. Un lieu de mémoire du projet « La Route de l'esclave » de l'UNESCO." },
  { id: 'arene', name: 'Arène de Ouidah', kind: 'Arène · Ouidah', k: 'monument', lat: 6.32425, lon: 2.09095, h: 22, view: [260, 0.98, 3.55],
    text: "L'arène en bord de mer, à deux pas de la Porte du Non-Retour, où se tiennent les cérémonies et les spectacles des Vodun Days, début janvier : piste de sable ocre, gradins aux sièges rouges sous des voiles blanches tendues, tribune officielle couverte et parvis côté ville." },
];
export const QUARTIERS = [
  ['Akpakpa', 6.3712, 2.4600], ['Cadjèhoun', 6.3615, 2.3975], ['Fidjrossè', 6.3555, 2.3690], ['Agla', 6.3760, 2.3680], ['Gbégamey', 6.3640, 2.4130],
  ['Zogbo', 6.3925, 2.3943], ['Ganhi', 6.3530, 2.4385], ['Jonquet', 6.3590, 2.4310], ['Sainte-Rita', 6.3795, 2.4132], ['Mènontin', 6.3885, 2.3736],
  ['Houéyiho', 6.3724, 2.3935], ['Placodji', 6.3505, 2.4320], ['Missèbo', 6.3660, 2.4352], ['Fifadji', 6.3935, 2.4010], ['Vossa', 6.3890, 2.4170],
  ['Ladji', 6.3910, 2.4300], ['Godomey', 6.3870, 2.3420], ['Les Cocotiers', 6.3520, 2.3900], ['Tokplégbé', 6.3660, 2.4905], ['Donaten', 6.3632, 2.4660],
  ['Avotrou', 6.3790, 2.4720], ['Midombo', 6.3790, 2.4430], ['Kouhounou', 6.3830, 2.3830], ['Gbèdjromèdé', 6.3840, 2.4200], ['Aïbatin', 6.3640, 2.3790],
  ['Abomey-Calavi', 6.4500, 2.3520], ['Zogbadjè', 6.4236, 2.3348], ['Togoudo', 6.4071, 2.3345], ['Kpota', 6.4440, 2.3560],
  ['Ouidah', 6.3620, 2.0850], ['Zoungbodji', 6.3405, 2.0889],
];
export const WATER_LABELS = [['Océan Atlantique', 6.326, 2.40], ['Lagune', 6.3805, 2.4435]];

